[package]
name = "amacs_example"
version = "0.1.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
edition = "2018"

[dependencies]
rand = "0.5"
sha3 = "0.7"
serde = "1"
serde_derive = "1"
merlin = "0.3"
curve25519-dalek = "0.19"
zkp = {git = "https://github.com/dalek-cryptography/zkp"}
