[package]
name = "amacs_example"
version = "0.1.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
edition = "2018"

[dependencies]
rand = "0.6"
sha3 = "0.8"
serde = "1"
serde_derive = "1"
merlin = "1"
curve25519-dalek = { version = "1.1", features = ["simd_backend"] }
zkp = "0.6"
